export enum Role {
  PACIENTE = 'PACIENTE',
  CUIDADOR = 'CUIDADOR',
  MEDICO = 'MEDICO',
  NAVEGADOR = 'NAVEGADOR',
  GESTOR_CLINICA = 'GESTOR_CLINICA',
  ANALISTA_OPERADORA = 'ANALISTA_OPERADORA',
  ADMIN = 'ADMIN',
}
